### ISSUE TITLE
Having Issues with Original Code 

### ISSUE THREAD

**Issue by protek-it** [lwhitelock/DattoRMM-Alert-HaloPSA#4]
Hey there, 

We have been working to move to HaloPSA with great success. Along the way we found mspp.io and your Github. We were successful on December 1st in getting this deployment working within our environment. An alert was getting generated in Halo I have attached a picture of that.

Now we are at the point where we would like the ticket to auto-resolve when the alert is closed in Datto. Upon hiring a dev and having them help us write the code to do this, we started reaching a snag in the Original Code. After troubleshooting his work for a few hours, we decided to spin up a fresh instance of this on a new resource to test. We are reaching the same error every time with the details of that error included. 

It seems to point to the convertfrom-json bit in the $alertwebhook variable 

Line: $AlertWebhook = $Request.Body | convertfrom-json -depth 100

We were hoping you could shed some light at why this may be happening.  

Please let me know if you would like any further information. 

![2022-12-23 12_10_41-Halo Alert](https://user-images.githubusercontent.com/112506003/209388441-4a338f26-ff0d-4de8-bc39-607afa42746a.png)
[funtionapp Log Stream.txt](https://github.com/lwhitelock/DattoRMM-Alert-HaloPSA/files/10296727/funtionapp.Log.Stream.txt)

**Comment by protek-it** [comment]
We were able to resolve this and also now we have the proper code to auto close the ticket as well. Please message us if you would like the code.

**Comment by lwhitelock** [comment]
Yea please, please submit a Pull Requst and I will have a look :)
